---
# fetch instance data from the metadata servers in ec2
- ec2_facts:

# show all known facts for this host
- debug: var=hostvars[inventory_hostname]

# just show the instance-id
- debug:
    msg: "{{ hostvars[inventory_hostname]['ansible_ec2_instance-id'] }}"

- name: Creating {{ app_name }} AMI
  ec2_ami:
    aws_access_key: "{{ ec2_access_key }}"
    aws_secret_key: "{{ ec2_secret_key }}"
    region: "{{ region }}"
    description: "{{ ami_description }}"
    instance_id: "{{ hostvars[inventory_hostname]['ansible_ec2_instance-id'] }}"
    wait: yes
    name: "{{ ami_name }}"
    state: present
